"""
Quick Demo - Run competitor analysis
Output langsung ke file untuk avoid Windows encoding issues
"""

import sys
sys.path.insert(0, '.')
sys.stdout.reconfigure(encoding='utf-8')

from SCRIPTS.prompt_runner import run_prompt
from pathlib import Path
import os

# Context untuk prompt
context = {
    "brand_name": "@somethinc",
    "platform": "Instagram",
    "handle": "@somethinc",
    "industry": "Skincare Indonesia",
    "posts_data": """
POST 1: "Kenapa kulit kusam? Ini 5 penyebabnya + solusinya!"
Likes: 8.5K | Comments: 234 | Saves: 1.2K | Format: Carousel

POST 2: "Glow check 3 bulan pakai vitamin C" (UGC)
Likes: 12K | Comments: 567 | Saves: 2.1K | Format: Reels

POST 3: "Cara layered skincare yang bener dari A-Z"
Likes: 15K | Comments: 890 | Saves: 3.4K | Format: Carousel

POST 4: "POV: Kamu baru sadar skincare kamu expired" (meme)
Likes: 18K | Comments: 1.2K | Saves: 892 | Format: Reels

POST 5: "Promo 12.12 - Diskon 30% semua produk!"
Likes: 3.2K | Comments: 145 | Saves: 89 | Format: Static
    """,
    "avg_likes": "9500",
    "avg_comments": "428",
    "avg_saves": "1200",
    "engagement_rate": "4.8"
}

print("=" * 60)
print("AtapDigital AI Prompt Library - Demo")
print("=" * 60)
print("\nRunning: Competitor Analysis untuk @somethinc")
print("-" * 60)

try:
    result = run_prompt(
        "PROMPTS/01_competitor_research/analyze_competitor.md",
        context=context,
        max_tokens=4096
    )

    # Save directly to file
    output_path = Path("EXAMPLES/sample_outputs/demo_output.md")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# AtapDigital AI Prompt Library - Demo Output\n\n")
        f.write("*Generated by AtapDigital AI Prompt Library*\n\n")
        f.write("---\n\n")
        f.write(result)

    print("\n[SUCCESS] Demo completed!")
    print(f"[SAVED] Output: {output_path}")
    print("\nContent preview (first 500 chars):")
    print("-" * 40)
    print(result[:500] + "...")

except Exception as e:
    print(f"\n[ERROR] {e}")
    import traceback
    traceback.print_exc()
